var day;
var desc0, desc1, desc2;
var cl0, cl1, cl2;
var startDateTime = new Date(2018, 2, 20, 11, 0, 0, 0);
var startStamp = startDateTime.getTime();
var timer;
var incweek = 0;
var d, h, m, s;
    
function setMisc(array) {
	if (array[0] == "Sanguine") {
        		imglink0 = "../img/sanguine.jpg"; 
        		desc0 = "• When slain, non-boss enemies leave behind a lingering pool of ichor that heals their allies and damages players";
        		cl0 = "green";
        //sanguine
		} else if (array[0] == "Bolstering") {
        		imglink0 = "../img/bolstering.jpg"; 
        		desc0 = "• When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%";
        		cl0 = "orange";
        //bolstering
		} else if (array[0] == "Raging") {
       			imglink0 = "../img/raging.jpg"; 
        		desc0 = "• Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated"; 
        		cl0 = "orange";
        //raging
		} else if (array[0] == "Teeming") {
        		imglink0 = "../img/teeming.jpg"; 
        		desc0 = "• Additional non-boss enemies are present throughout the dungeon";
        		cl0 = "orange";
        //teeming
		} else if (array[0] == "Bursting") {
        		imglink0 = "../img/bursting.jpg"; 
        		desc0 = "• When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks"
        		cl0 = "orange";
        //bursting
		}

// ------------------------------------------------------------------ //

		if (array[1] == "Necrotic" ) {
			imglink1 = "../img/necrotic.jpg"; 
        		desc1 = "• All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received";
        		cl1 = "red";
        //necrotic
		} else if (array[1] == "Skittish" ) {
        		imglink1 = "../img/skittish.jpg"; 
        		desc1 = "• Enemies pay far less attention to threat generated by tanks";
        		cl1 = "orange";
        //skittish
		} else if (array[1] == "Volcanic" ) {
        		imglink1 = "../img/volcanic.jpg"; 
        		desc1 = "• While in combat, enemies periodically cause gouts of flame to erupt beneath the feet of distant players"; 
        		cl1 = "green";
        //volcanic
		} else if (array[1] == "Explosive" ) {
        		imglink1 = "../img/explosive.jpg"; 
        		desc1 = "• While in combat, enemies periodically summon Explosive Orbs that will detonate if not destroyed";
        		cl1 = "orange";
        //explosive
		} else if (array[1] == "Quaking" ) {
        		imglink1 = "../img/quaking.jpg"; 
        		desc1 = "• Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies";
        		cl1 = "green";
        //quaking
		} else if (array[1] == "Grevious" ) {
        		imglink1 = "../img/grevious.jpg"; 
        		desc1 = "• When injured below 90% health, players will suffer increasing damage over time until healed above 90% health";
        		cl1 = "orange";
		}

// ------------------------------------------------------------------ //

		if (array[2] == "Fortified" ) {
        		imglink2 = "../img/fortified.jpg"; 
        		desc2 = "• Non-boss enemies have 20% more health and inflict up to 30% increased damage";
        		cl2 = "orange";
        //fortified
		} else if (array[2] == "Tyrannical" ) {
        		imglink2 = "../img/tyrannical.jpg"; 
        		desc2 = "• Boss enemies have 40% more health and inflict up to 15% increased damage";
        		cl2 = "red";
        //tyrannical
		}
}
	function daysInMonth (month, year) {
    		return new Date(year, month, 0).getDate();
	}
    
function updateHeader() {
    		newDate = new Date();
    		newStamp = newDate.getTime();
    		var diff = Math.round((newStamp-startStamp)/1000);
    
     		d = Math.floor(diff/(24*60*60));
    		diff = diff-(d*24*60*60);
    		h = Math.floor(diff/(60*60));
    		diff = diff-(h*60*60);
    		m = Math.floor(diff/(60));
    		diff = diff-(m*60);
    		s = diff;
    
    		if (d/7 >= 1) {
    			startDateTimedate = startDateTime.getDate() + 7;
        		if (startDateTimedate > daysInMonth(startDateTime.getMonth+1, startDateTime.getFullYear)) {
        			startDateTime.setDate(startDateTimedate - daysInMonth(startDateTime.getMonth+1, startDateTime.getFullYear));
        			startDateTime.setMonth(startDateTime.getMonth+1);
        		} else { 
        			startDateTime.setDate(startDateTimedate);
        		}
        		startStamp = startDateTime.getTime();
        		incweek = incweek + 1;
        		if (incweek == 11) {
        			incweek = 0;
        		}
        			updateHeader()
    		} else {
    		}

    		allweeks = [["Sanguine", "Necrotic", "Fortified"], ["Bursting", "Skittish", "Tyrannical"], ["Teeming", "Quaking", "Fortified"], ["Raging", "Necrotic", "Tyrannical"], ["Bolstering", "Skittish", "Fortified"], ["Teeming", "Volcanic", "Tyrannical"], ["Sanguine", "Grevious", "Fortified"], ["Bolstering", "Explosive", "Tyrannical"], ["Bursting", "Quaking", "Fortified"],["Raging", "Volcanic", "Tyrannical"], ["Teeming", "Explosive", "Fortified"], ["Bolstering", "Grevious", "Tyrannical"]];

		thisweek = allweeks[incweek];
		nextweek = allweeks[incweek+1];
		twoweeks = allweeks[incweek+2];
	
		setMisc(thisweek);
	
		document.getElementById('tw1').src = imglink0;
		document.getElementById('tw2').src = imglink1;
		document.getElementById('tw3').src = imglink2;
		
		setMisc(nextweek);
		
		document.getElementById('nw1').src = imglink0;
		document.getElementById('nw2').src = imglink1;
		document.getElementById('nw3').src = imglink2;
		
		setMisc(twoweeks);
		document.getElementById('an1').src = imglink0;
		document.getElementById('an2').src = imglink1;
		document.getElementById('an3').src = imglink2;
	}

